"use client";

import { useEffect, useRef, useState } from "react";

export default function About() {
  const [isVisible, setIsVisible] = useState(false);
  const sectionRef = useRef<HTMLElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
        }
      },
      { threshold: 0.3 }
    );

    if (sectionRef.current) {
      observer.observe(sectionRef.current);
    }

    return () => observer.disconnect();
  }, []);

  return (
    <section ref={sectionRef} className="relative bg-gray-50 py-32 lg:py-40">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        {/* Enhanced Section Header with Apple-style spacing */}
        <div
          className={`mx-auto max-w-4xl text-center mb-24 transition-all duration-1000 ease-out ${
            isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-12"
          }`}
        >
          <div className="mb-8">
            <p className="text-sm font-medium text-gray-500 tracking-wider uppercase mb-4">
              About Adlaan
            </p>
            <h2 className="text-4xl sm:text-5xl lg:text-6xl font-extralight text-gray-900 leading-tight tracking-[-0.02em] mb-8">
              Built on the Principle of{" "}
              <span className="italic text-gray-700">ʿAdl</span>
            </h2>
            <div className="w-32 h-px bg-gradient-to-r from-transparent via-gray-300 to-transparent mx-auto mb-8"></div>
            <p className="text-xl lg:text-2xl font-light text-gray-600 leading-relaxed max-w-3xl mx-auto">
              Pioneering the future of legal technology through Arabic-rooted AI
              intelligence, where every document embodies justice and balance.
            </p>
          </div>
        </div>

        {/* Main Content with enhanced visual hierarchy */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-16 lg:gap-20 items-start">
          {/* Left Content - Apple-style content blocks */}
          <div className="lg:col-span-7 space-y-12">
            {/* First content block */}
            <div
              className={`transition-all duration-1000 delay-200 ease-out ${
                isVisible
                  ? "opacity-100 translate-y-0"
                  : "opacity-0 translate-y-8"
              }`}
            >
              <div className="space-y-6">
                <h3 className="text-2xl lg:text-3xl font-light text-gray-900 leading-tight">
                  Justice in Every Algorithm
                </h3>
                <p className="text-lg text-gray-600 leading-relaxed">
                  Adlaan represents more than advanced AI technology—it embodies
                  the Arabic concept of{" "}
                  <span className="font-medium text-gray-900 bg-gray-100 px-2 py-1 rounded">
                    ʿadl
                  </span>{" "}
                  (justice), ensuring every legal document is not just accurate,
                  but fundamentally fair and balanced.
                </p>
                <p className="text-lg text-gray-600 leading-relaxed">
                  Our platform synthesizes centuries of legal wisdom with
                  cutting-edge AI, creating documentation that serves both
                  commercial needs and ethical standards.
                </p>
              </div>
            </div>

            {/* Second content block */}
            <div
              className={`transition-all duration-1000 delay-400 ease-out ${
                isVisible
                  ? "opacity-100 translate-y-0"
                  : "opacity-0 translate-y-8"
              }`}
            >
              <div className="space-y-6">
                <h3 className="text-2xl lg:text-3xl font-light text-gray-900 leading-tight">
                  Arabic-Rooted Intelligence
                </h3>
                <p className="text-lg text-gray-600 leading-relaxed">
                  Drawing from rich Arabic legal traditions and Islamic
                  jurisprudence, our AI understands not just the letter of the
                  law, but its spirit—creating agreements that honor both modern
                  business practices and timeless principles of fairness.
                </p>
              </div>
            </div>

            {/* Third content block */}
            <div
              className={`transition-all duration-1000 delay-600 ease-out ${
                isVisible
                  ? "opacity-100 translate-y-0"
                  : "opacity-0 translate-y-8"
              }`}
            >
              <div className="space-y-6">
                <h3 className="text-2xl lg:text-3xl font-light text-gray-900 leading-tight">
                  Precision Meets Purpose
                </h3>
                <p className="text-lg text-gray-600 leading-relaxed">
                  Every contract, policy, and agreement generated by Adlaan
                  undergoes rigorous AI review to ensure legal soundness,
                  clarity, and ethical integrity—delivering documents that
                  protect all parties while fostering trust and transparency.
                </p>
              </div>
            </div>
          </div>

          {/* Right Content - Enhanced visual elements */}
          <div className="lg:col-span-5">
            <div
              className={`sticky top-24 transition-all duration-1000 delay-800 ease-out ${
                isVisible
                  ? "opacity-100 translate-y-0"
                  : "opacity-0 translate-y-8"
              }`}
            >
              {/* Key principles card */}
              <div className="bg-white rounded-3xl p-8 shadow-xl shadow-gray-200/50 border border-gray-100">
                <h4 className="text-xl font-medium text-gray-900 mb-8">
                  Core Principles
                </h4>

                <div className="space-y-6">
                  <div className="flex items-start space-x-4">
                    <div className="w-2 h-2 bg-gray-400 rounded-full mt-3 flex-shrink-0"></div>
                    <div>
                      <h5 className="font-medium text-gray-900 mb-2">
                        Justice (ʿAdl)
                      </h5>
                      <p className="text-sm text-gray-600 leading-relaxed">
                        Ensuring fairness and balance in every legal document
                      </p>
                    </div>
                  </div>

                  <div className="flex items-start space-x-4">
                    <div className="w-2 h-2 bg-gray-400 rounded-full mt-3 flex-shrink-0"></div>
                    <div>
                      <h5 className="font-medium text-gray-900 mb-2">
                        Precision (Itqan)
                      </h5>
                      <p className="text-sm text-gray-600 leading-relaxed">
                        Meticulous attention to legal detail and accuracy
                      </p>
                    </div>
                  </div>

                  <div className="flex items-start space-x-4">
                    <div className="w-2 h-2 bg-gray-400 rounded-full mt-3 flex-shrink-0"></div>
                    <div>
                      <h5 className="font-medium text-gray-900 mb-2">
                        Wisdom (Hikmah)
                      </h5>
                      <p className="text-sm text-gray-600 leading-relaxed">
                        Integrating traditional legal wisdom with modern
                        innovation
                      </p>
                    </div>
                  </div>

                  <div className="flex items-start space-x-4">
                    <div className="w-2 h-2 bg-gray-400 rounded-full mt-3 flex-shrink-0"></div>
                    <div>
                      <h5 className="font-medium text-gray-900 mb-2">
                        Trust (Amanah)
                      </h5>
                      <p className="text-sm text-gray-600 leading-relaxed">
                        Building reliable, transparent legal processes
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Stats or additional info */}
              <div className="mt-8 grid grid-cols-2 gap-4">
                <div className="bg-gray-900 rounded-2xl p-6 text-white">
                  <div className="text-3xl font-light mb-2">99.7%</div>
                  <div className="text-sm text-gray-300">Legal Accuracy</div>
                </div>
                <div className="bg-gray-900 rounded-2xl p-6 text-white">
                  <div className="text-3xl font-light mb-2">15min</div>
                  <div className="text-sm text-gray-300">Avg. Processing</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
