# Google App Engine configuration for Adlaan Django Web App
runtime: python39

env_variables:
  DJANGO_SETTINGS_MODULE: "adlaan_project.settings"
  SECRET_KEY: "your-secret-key-here"
  DEBUG: "False"

automatic_scaling:
  min_instances: 1
  max_instances: 10

handlers:
- url: /static
  static_dir: adlaan-web/static

- url: /.*
  script: auto
  secure: always

entrypoint: gunicorn -b :$PORT adlaan_project.wsgi:application --chdir adlaan-web