#!/bin/bash
echo "=== TESTING ENHANCED ADLAAN LEGAL AI ==="
echo ""
echo "✅ Server Status:"
ss -tlnp | grep :8005 && echo "Server running on port 8005"
echo ""
echo "✅ Interface Ready:"
echo "Chat Interface: http://127.0.0.1:8005/chat"
echo "API Documentation: http://127.0.0.1:8005/docs"
echo ""
echo "🎯 Test Queries:"
echo "• 'Jordan business license requirements'"
echo "• 'Create a rental agreement'"
echo "• 'Draft an NDA for tech company'"
echo "• 'Employment contract template'"
echo ""
echo "📄 Enhanced Features:"
echo "✓ Direct responses (no unnecessary questions)"
echo "✓ Automatic document generation"
echo "✓ Clean output (no JSON artifacts)"
echo "✓ Immediate document panel updates"
echo "✓ Simplified thinking indicator"
echo "✓ Professional legal formatting"
echo ""
echo "Ready for testing! 🚀"